FROM node:22.4.1-alpine
# Set working directory
WORKDIR /app

COPY package*.json ./

RUN npm install

# Copy all source files
COPY . .



EXPOSE 3003

HEALTHCHECK --interval=30s --timeout=3s \
  CMD node healthcheck.js || exit 1

# Run the application
CMD ["node", "index.js"]