FROM node:22.4.1-alpine
# Set working directory
WORKDIR /app


COPY package*.json ./

# Install dependencies 
RUN npm install

# Copy all source files
COPY . .

# Expose the port your Express app uses
EXPOSE 3001


HEALTHCHECK --interval=30s --timeout=3s \
  CMD node healthcheck.js || exit 1

# Run the application
CMD ["node", "index.js"]